[package]
name = "rcommon"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
nix = "0.25.0"
unic-langid = "*"
fluent = "*"
fluent-bundle = "*"
fluent-resmgr = "*"
#rhelp = {path ="../help"}

[lib]
crate-type = ["staticlib","rlib"]
name = "rcommon"
