[package]
name = "r_readline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcommon = {path = "../builtins_rust/common"}

[lib]
name = "r_readline"
crate-type = ["rlib", "staticlib"]