[package]
name = "utshell"
version = "1.0.0"
edition = "2018"

build = "./build.rs"  

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
lazy_static = "1.4.0"
#fluent = "*"
unic-langid = "0.9.4"
fluent-resmgr = "0.0.6"
fluent-bundle = "0.15.2"
intl_pluralrules = "7.0.2"
tinystr = "=0.7.1"


[build-dependencies]
dunce = "1.0.0" 

[profile.release]
lto = false
opt-level = 0
codegen-units = 1

[lib]
name = "builtins"
path = "src/lib.rs"
crate-type = ["staticlib","rlib"]

[[bin]]
name = "utshell"
path = "src/main.rs"

[[bin]]
name = "utshellversion"
path = "src/utshellversion.rs"
