[package]
name = "rreturn"
version = "0.1.0"
edition = "2018"
authors = ["lvgenggeng"]
#build = "../build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rreturn"
crate-type = ["staticlib","rlib"]

[dependencies]
libc = "*"
nix = "0.25.0"
rcommon = {path = "../common"}
rhelp = {path ="../help"}
